wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.4
      5: 0.10.27
      8:
      - 5
batch_size:
  desc: null
  value: 24
ci:
  desc: null
  value: 0
client_num_in_total:
  desc: null
  value: 3
client_num_per_round:
  desc: null
  value: 3
client_optimizer:
  desc: null
  value: adam
comm_round:
  desc: null
  value: 30
dataset:
  desc: null
  value: type10
do:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 1
frequency_of_the_test:
  desc: null
  value: 3
gpu:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.0005
model:
  desc: null
  value: lf
n_features:
  desc: null
  value: 27
n_hidden:
  desc: null
  value: 500
n_layers:
  desc: null
  value: 2
out_features:
  desc: null
  value: 96
seq_len:
  desc: null
  value: 672
type_num:
  desc: null
  value: 10
wd:
  desc: null
  value: 0.001
